name: Get FAA registration data

on:
  push:
    paths:
      - .github/workflows/scrape-faa-website.yaml # Only run a new workflow every time this file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '0 7 * * *' # Run at 0700Z

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Fetch latest data
        run: |-
          curl -O https://registry.faa.gov/database/ReleasableAircraft.zip
      - name: Unzip
        run: |-
          unzip -o ReleasableAircraft.zip
      - name: Remove spaces
        run: |-
          for i in *.txt; do sed -i -E 's/, +/,/g' $i && sed -i -E 's/ +,/,/g' $i; done
      - name: Commit and push if it changed
        # See https://stackoverflow.com/a/59926487/122762 for an explanation
        # of the postBuffer increase.
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git config --global http.postBuffer 157286400
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
